require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/subs", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Sub. As you add validations to Sub, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Sub.create! valid_attributes
      get subs_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      sub = Sub.create! valid_attributes
      get sub_url(sub)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_sub_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      sub = Sub.create! valid_attributes
      get edit_sub_url(sub)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Sub" do
        expect {
          post subs_url, params: { sub: valid_attributes }
        }.to change(Sub, :count).by(1)
      end

      it "redirects to the created sub" do
        post subs_url, params: { sub: valid_attributes }
        expect(response).to redirect_to(sub_url(Sub.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Sub" do
        expect {
          post subs_url, params: { sub: invalid_attributes }
        }.to change(Sub, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post subs_url, params: { sub: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested sub" do
        sub = Sub.create! valid_attributes
        patch sub_url(sub), params: { sub: new_attributes }
        sub.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the sub" do
        sub = Sub.create! valid_attributes
        patch sub_url(sub), params: { sub: new_attributes }
        sub.reload
        expect(response).to redirect_to(sub_url(sub))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        sub = Sub.create! valid_attributes
        patch sub_url(sub), params: { sub: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested sub" do
      sub = Sub.create! valid_attributes
      expect {
        delete sub_url(sub)
      }.to change(Sub, :count).by(-1)
    end

    it "redirects to the subs list" do
      sub = Sub.create! valid_attributes
      delete sub_url(sub)
      expect(response).to redirect_to(subs_url)
    end
  end
end
